### ISSUE TITLE
Pattern match failure on ENCAP * GCAP

### ISSUE THREAD

**Issue by Xe** [shockkolate/arata#4]
On my local machine I have a second client node set up to simluate a better test network. While testing arata today I noticed this:

```
-> :649 SID cbbouaf6saroyvk5.onion 2 0NI :(H) anonymous tor proxy
-> :0NI ENCAP * GCAP :QS EX CHW IE KLN KNOCK TB UNKLN CLUSTER ENCAP SERVICES RSFNC SAVE EUID EOPMOD BAN MLOCK
Disconnected
user error (Pattern match failure in do expression at src/Arata/Protocol/Charybdis.hs:101:5-12) 
```

I will be making a patch for this shortly.

**Comment by ori-sky** [comment]
Actually, I've reopened this issue because I'm certain some situation will arise in which Arata needs to act on an ENCAP command received directly from a server as opposed to a client. The commit Xe referenced this issue from (https://github.com/Xe/arata/commit/d43f2d1bd3b0e43350d29eed3c8b6dee77d0a22c) doesn't seem like an appropriate starting point for a solution to this issue, however.

What I've had in mind for a while now--without the need for it yet--is for `Client` to be a constructor of a new type `Source` or perhaps for `Source` to be a type class and for an instance of `Source` to be written for `Client`. A `Server` constructor or type would be implemented in just the same way and a value of type `Server` would be usable anywhere that takes a `Source` or type instancing `Source`.

I'm leaning towards the type class design simply because it feels to me like it would be a more elegant solution.

**Comment by ori-sky** [comment]
After consideration and much experimentation, the best course of action seems to be to implement `Source` as a type rather than as a type class. Once a function has only a value of generic type variable `a`, bounded by `Source a`, there's no elegant way for that function to get a `Client` or `Server` value from it (or any type that instances `Source`).

Besides, I can't think of any reason for a third-party module to need to instance `Source` when both `Client` and `Server` would exist.

**Comment by Xe** [comment]
864bf5a6e07a10e69e76308a2d93298eb83b0894 should render this issue solved.
